"""Refactor_Scenario_schema

Revision ID: 1d2e5ab1264d
Revises: 874056258d3c
Create Date: 2026-02-09 14:29:08.819522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d2e5ab1264d'
down_revision: Union[str, Sequence[str], None] = '874056258d3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('world_asset_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))
    op.drop_column('scenarios', 'default_world_data')
    op.drop_column('scenarios', 'base_system_prompt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('base_system_prompt', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('scenarios', sa.Column('default_world_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('scenarios', 'world_asset_data')
    # ### end Alembic commands ###
