"""Rename_world_snapshot_to_state

Revision ID: d9273ffddd56
Revises: 1d2e5ab1264d
Create Date: 2026-02-09 15:08:35.050999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9273ffddd56'
down_revision: Union[str, Sequence[str], None] = '1d2e5ab1264d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('world_state_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('games', 'world_data_snapshot')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('world_data_snapshot', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('games', 'world_state_data')
    # ### end Alembic commands ###
