"""Rename_world_snapshot_to_state_and_fix_memory

Revision ID: dc3e5fc3a012
Revises: d9273ffddd56
Create Date: 2026-02-09 15:09:06.754465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc3e5fc3a012'
down_revision: Union[str, Sequence[str], None] = 'd9273ffddd56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
